name: Cinesub Auto Scraper

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Install Chrome
      run: npx puppeteer browsers install chrome

    - name: Run Scraper
      run: node scraper.js

    # සීරපු දත්ත ලියාපදිංචි කර ඩවුන්ලෝඩ් කරගත හැකි ගොනුවක් (Artifact) ලෙස සුරැකීම
    - name: Upload Movies Data File
      uses: actions/upload-artifact@v4
      with:
        name: cinesub-movies-data
        path: movies.json
